# -*- coding: utf-8 -*-
"""Hacklytics Poker Project .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CedYq8Nlr-nAIXVWKDFnkDkzgUJzxEE_
"""

import numpy as np
import pandas as pd
import random
from scipy.stats import norm
from scipy.stats import uniform
import requests
import json

np.random.seed(41)
ev_array = np.random.normal(-10, 50, size=(100, 4000))
ev_array

ELO_array = np.zeros(100)
for player in range(len(ev_array)):
  ELO_array[player] = (1.2*np.sum(ev_array[player][:2000]/2000)) + (1.1 * np.sum(ev_array[player][2001:3000]/1000))+  (np.sum(ev_array[player][3001:4000]/1000))
ELO_array += 100
ELO_array.min(), ELO_array.max()

api_key = "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"
endpoint = "https://api.openai.com/v1/completions"
prompt = "Once upon a time, in a far-off land, there was a young prince named John."
params = {"model": "text-davinci-003","prompt": prompt,"max_tokens": 50}
headers = {"Authorization": f"Bearer {api_key}","Content-Type": "application/json"}
response = requests.post(endpoint, data=json.dumps(params), headers=headers)
if response.status_code == 200:
    print("API call successful.")
    print("Response:")
    print(response.json())
else:
    print(f"API call failed with status code {response.status_code}.")
    print("Error message:")
    print(response.text)

